#include "include/entity_event.h"


const EventType ENTITY_MOVE_FW_START 		= EventType("ENTITY_MOVE_FW_START");
const EventType ENTITY_MOVE_FW_END 			= EventType("ENTITY_MOVE_FW_END");
const EventType ENTITY_MOVE_BW_START 		= EventType("ENTITY_MOVE_BW_START");
const EventType ENTITY_MOVE_BW_END 			= EventType("ENTITY_MOVE_BW_END");
const EventType ENTITY_STRAFE_LEFT_START 	= EventType("ENTITY_STRAFE_LEFT_START");
const EventType ENTITY_STRAFE_LEFT_END 		= EventType("ENTITY_STRAFE_LEFT_END");
const EventType ENTITY_STRAFE_RIGHT_START 	= EventType("ENTITY_STRAFE_RIGHT_START");
const EventType ENTITY_STRAFE_RIGHT_END 	= EventType("ENTITY_STRAFE_RIGHT_END");
const EventType ENTITY_TURN_LEFT_START 		= EventType("ENTITY_TURN_LEFT_START");
const EventType ENTITY_TURN_LEFT_END 		= EventType("ENTITY_TURN_LEFT_END");
const EventType ENTITY_TURN_RIGHT_START 	= EventType("ENTITY_TURN_RIGHT_START");
const EventType ENTITY_TURN_RIGHT_END 		= EventType("ENTITY_TURN_RIGHT_END");
const EventType ENTITY_JUMP_START			= EventType("ENTITY_JUMP_START");
const EventType ENTITY_JUMP_END				= EventType("ENTITY_JUMP_END");
const EventType ENTITY_ROTATE_BY 			= EventType("ENTITY_ROTATE_BY");

const std::vector<EventType> ENTITY_MOVE_START	= {
	ENTITY_MOVE_FW_START,
	ENTITY_MOVE_BW_START,
	ENTITY_STRAFE_LEFT_START,
	ENTITY_STRAFE_RIGHT_START,
	ENTITY_TURN_LEFT_START,
	ENTITY_TURN_RIGHT_START,
	ENTITY_JUMP_START
};
const std::vector<EventType> ENTITY_MOVE_END	= {
	ENTITY_MOVE_FW_END,
	ENTITY_MOVE_BW_END,
	ENTITY_STRAFE_LEFT_END,
	ENTITY_STRAFE_RIGHT_END,
	ENTITY_TURN_LEFT_END,
	ENTITY_TURN_RIGHT_END,
	ENTITY_JUMP_END
};
